use schedule;

DROP TABLE IF EXISTS Teachers;
DROP TABLE IF EXISTS Absences;
DROP TABLE IF EXISTS SubjectTypes;
DROP TABLE IF EXISTS Subjects;
DROP TABLE IF EXISTS Equipment;
DROP TABLE IF EXISTS SubEquip;
DROP TABLE IF EXISTS Rooms;
DROP TABLE IF EXISTS RoomEquip;
DROP TABLE IF EXISTS Groups;
DROP TABLE IF EXISTS SubGroup;
DROP TABLE IF EXISTS TeachGroup;
DROP TABLE IF EXISTS Students;
DROP TABLE IF EXISTS StudGroup;
DROP TABLE IF EXISTS Properties;
# DROP TABLE IF EXISTS Buildings;
